name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install prettier
      - run: npm install --save-dev --save-exact prettier
      - name: Run prettier
      - run: npx prettier --single-attribute-per-line true --use-tabs true --write **/*.{js,cjs,ts,jsx,tsx,json,md}
